server:
  port: 5053
debug: true
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: OAuth2-Server
  cloud:
    compatibility-verifier:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1045782700258-t0bs0cus78l4qklvod2nhb2gtugdigpp.apps.googleusercontent.com
            client-secret: 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
          
jwt:
  secret= mysecretkey
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
      
logging:
  file:
    name: C:/Users/pardpath/OneDrive - Cisco/Desktop/Project Files/logs/O-Auth2-Service.log
#  level:
#    root: INFO
#  pattern:
#    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
#  console:  "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
#  
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
  circuitbreaker:
    instances:
      studentcontr:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      studentcontr:
        maxRetryAttempts: 5
        waitDuration: 10s
  ratelimiter:
    instances:
      studentcontr:
        registerHealthIndicator: true
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
        
#okta:
#  oauth2:
#    issuer: https://dev-69836709.okta.com/oauth2/default
# 
#    client-id: 0oa76a1f1mSPARFyq5d7
#    
#    client-secret: -1jVBdxOJjt5ppP5FhFg00vQhBqhr5TCHY4Juc0B
